name: Metrics

on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get remove -y containerd
          sudo apt-get install -y docker.io jq build-essential libxml2-dev libxslt-dev

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run GitHub Metrics
        uses: Grantglass/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
